language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t dimegliopablo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dimegliopablo/docker-react npm run test